### ISSUE TITLE
docker-compose.yml: `version` is obsolete

### ISSUE THREAD

**Issue by ghost** [JouniMi/TheDFIRThing#2]
Hey,

Do you know why this is getting an error?

Docker version: 4.32

`root@batpc:~/TheDFIRThing# docker-compose up -d
WARN[0000] /root/TheDFIRThing/docker-compose.yml: `version` is obsolete
[+] Running 4/4
 ✘ Container elasticsearch  Error                                                                                 10.1s
 ✔ Container kibana         Running                                                                                0.0s
 ✔ Container filebeat       Running                                                                                0.0s
 ✔ Container logstash       Running                                                                                0.0s
dependency failed to start: container elasticsearch exited (1)
root@batpc:~/TheDFIRThing# nano docker-compose.yml
root@batpc:~/TheDFIRThing# nano docker-compose.yml
root@batpc:~/TheDFIRThing# docker-compose up -d
WARN[0000] /root/TheDFIRThing/docker-compose.yml: `version` is obsolete
[+] Running 4/4
 ✘ Container elasticsearch  Error                                                                                 10.6s
 ✔ Container kibana         Running                                                                                0.0s
 ✔ Container filebeat       Running                                                                                0.0s
 ✔ Container logstash       Started                                                                                0.0s
dependency failed to start: container elasticsearch exited (1)
root@batpc:~/TheDFIRThing#`

**Comment by JouniMi** [comment]
Hey! The version parameter is not used anymore in the latest versions of docker compose, the files which I've created have been created long time ago so that it still present. However, that should not cause the issue which you are facing, rather it is informational. I also don't want to remove the version line as there still are a lot of older docker-composes around which won't work without that line. You can remove the Version line from the docker-compose.yml file and try it out but it shouldn't fix the issue.

Sounds like the elasticsearch container itself is not starting correctly. Have you run _docker-compose ps_ command to see the exit code? Another good option for debugging is to start the containers and then see the logs from the elasticsearch container: _docker-compose logs elasticsearch_

**Comment by ghost** [comment]
Hey, I just reinstalled the project, and now it works. I didn't know what was happening. Thanks for your reply :)
